vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
        
    mappings:
        produits:
            uri_prefix: /images/produits
            upload_destination: '%kernel.project_dir%/public/images/produits'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
